Initial Classes
Dhii/exception pull request #1
Opened 2017-07-29 19:11 UTC by XedinUnknown

Added `Exception` and `InvalidArgumentException` standards-compliant classes.

2017-08-19 08:52 UTC, XedinUnknown commented
@mecha, could you review this PR please?

2017-08-19 10:29 UTC, mecha requested changes

2017-08-19 10:29 UTC, mecha commented on src/InvalidArgumentException.php
> +    public function __construct($message = '', $code = 0, RootException $previous = null, $argument = null)
Documentation required.

2017-08-19 10:29 UTC, mecha commented on src/InvalidArgumentException.php
> +    protected function _setArgument($argument)
Parameter doc missing.

2017-08-19 10:31 UTC, mecha commented on test/functional/InvalidArgumentExceptionTest.php
> +            $this->assertEquals($message, $e->getMessage(), 'Subject message is wrong');
I think an argument can be made that. given that this is a functional test, these assertions are not required as they have already been included in `ExceptionTest`.

2017-08-19 10:36 UTC, XedinUnknown commented on test/functional/InvalidArgumentExceptionTest.php
> +            $this->assertEquals($message, $e->getMessage(), 'Subject message is wrong');
I thought about that. But on the other hand, this is a different concrete class, with a different constructor, which sets the internal properties, and therefore needs to be tested separately.

2017-08-19 10:37 UTC, XedinUnknown commented
- [ ] @XedinUnknown to add missing docs.

2017-09-03 09:32 UTC, mecha approved these changes
LGTM

2017-09-05 07:36 UTC, merged